/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ToolBarcodeGeneratorRouteImport } from './routes/_tool/barcode-generator'
import { Route as ToolBleedGeneratorRouteImport } from './routes/_tool/bleed-generator'
import { Route as ToolBookletImpositionRouteImport } from './routes/_tool/booklet-imposition'
import { Route as ToolCmykPlatesRouteImport } from './routes/_tool/cmyk-plates'
import { Route as ToolDielineRouteImport } from './routes/_tool/dieline'
import { Route as ToolDpiCalculatorRouteImport } from './routes/_tool/dpi-calculator'
import { Route as ToolFoldSimulatorRouteImport } from './routes/_tool/fold-simulator'
import { Route as ToolLegibilityRouteImport } from './routes/_tool/legibility'
import { Route as ToolNestingCalcRouteImport } from './routes/_tool/nesting-calc'
import { Route as ToolPdfToolsRouteImport } from './routes/_tool/pdf-tools'
import { Route as ToolRgbToCmykRouteImport } from './routes/_tool/rgb-to-cmyk'
import { Route as ToolScreenPrintRouteImport } from './routes/_tool/screen-print'
import { Route as ToolSpineCalculatorRouteImport } from './routes/_tool/spine-calculator'
import { Route as ToolSpotFinishRouteImport } from './routes/_tool/spot-finish'
import { Route as ToolTacCheckerRouteImport } from './routes/_tool/tac-checker'
import { Route as ToolTextileGuideRouteImport } from './routes/_tool/textile-guide'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolBarcodeGeneratorRoute = ToolBarcodeGeneratorRouteImport.update({
  id: '/_tool/barcode-generator',
  path: '/barcode-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolBleedGeneratorRoute = ToolBleedGeneratorRouteImport.update({
  id: '/_tool/bleed-generator',
  path: '/bleed-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolBookletImpositionRoute = ToolBookletImpositionRouteImport.update({
  id: '/_tool/booklet-imposition',
  path: '/booklet-imposition',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolCmykPlatesRoute = ToolCmykPlatesRouteImport.update({
  id: '/_tool/cmyk-plates',
  path: '/cmyk-plates',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolDielineRoute = ToolDielineRouteImport.update({
  id: '/_tool/dieline',
  path: '/dieline',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolDpiCalculatorRoute = ToolDpiCalculatorRouteImport.update({
  id: '/_tool/dpi-calculator',
  path: '/dpi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolFoldSimulatorRoute = ToolFoldSimulatorRouteImport.update({
  id: '/_tool/fold-simulator',
  path: '/fold-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolLegibilityRoute = ToolLegibilityRouteImport.update({
  id: '/_tool/legibility',
  path: '/legibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolNestingCalcRoute = ToolNestingCalcRouteImport.update({
  id: '/_tool/nesting-calc',
  path: '/nesting-calc',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolPdfToolsRoute = ToolPdfToolsRouteImport.update({
  id: '/_tool/pdf-tools',
  path: '/pdf-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolRgbToCmykRoute = ToolRgbToCmykRouteImport.update({
  id: '/_tool/rgb-to-cmyk',
  path: '/rgb-to-cmyk',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolScreenPrintRoute = ToolScreenPrintRouteImport.update({
  id: '/_tool/screen-print',
  path: '/screen-print',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSpineCalculatorRoute = ToolSpineCalculatorRouteImport.update({
  id: '/_tool/spine-calculator',
  path: '/spine-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSpotFinishRoute = ToolSpotFinishRouteImport.update({
  id: '/_tool/spot-finish',
  path: '/spot-finish',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolTacCheckerRoute = ToolTacCheckerRouteImport.update({
  id: '/_tool/tac-checker',
  path: '/tac-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolTextileGuideRoute = ToolTextileGuideRouteImport.update({
  id: '/_tool/textile-guide',
  path: '/textile-guide',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/barcode-generator': typeof ToolBarcodeGeneratorRoute
  '/bleed-generator': typeof ToolBleedGeneratorRoute
  '/booklet-imposition': typeof ToolBookletImpositionRoute
  '/cmyk-plates': typeof ToolCmykPlatesRoute
  '/dieline': typeof ToolDielineRoute
  '/dpi-calculator': typeof ToolDpiCalculatorRoute
  '/fold-simulator': typeof ToolFoldSimulatorRoute
  '/legibility': typeof ToolLegibilityRoute
  '/nesting-calc': typeof ToolNestingCalcRoute
  '/pdf-tools': typeof ToolPdfToolsRoute
  '/rgb-to-cmyk': typeof ToolRgbToCmykRoute
  '/screen-print': typeof ToolScreenPrintRoute
  '/spine-calculator': typeof ToolSpineCalculatorRoute
  '/spot-finish': typeof ToolSpotFinishRoute
  '/tac-checker': typeof ToolTacCheckerRoute
  '/textile-guide': typeof ToolTextileGuideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/barcode-generator': typeof ToolBarcodeGeneratorRoute
  '/bleed-generator': typeof ToolBleedGeneratorRoute
  '/booklet-imposition': typeof ToolBookletImpositionRoute
  '/cmyk-plates': typeof ToolCmykPlatesRoute
  '/dieline': typeof ToolDielineRoute
  '/dpi-calculator': typeof ToolDpiCalculatorRoute
  '/fold-simulator': typeof ToolFoldSimulatorRoute
  '/legibility': typeof ToolLegibilityRoute
  '/nesting-calc': typeof ToolNestingCalcRoute
  '/pdf-tools': typeof ToolPdfToolsRoute
  '/rgb-to-cmyk': typeof ToolRgbToCmykRoute
  '/screen-print': typeof ToolScreenPrintRoute
  '/spine-calculator': typeof ToolSpineCalculatorRoute
  '/spot-finish': typeof ToolSpotFinishRoute
  '/tac-checker': typeof ToolTacCheckerRoute
  '/textile-guide': typeof ToolTextileGuideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_tool/barcode-generator': typeof ToolBarcodeGeneratorRoute
  '/_tool/bleed-generator': typeof ToolBleedGeneratorRoute
  '/_tool/booklet-imposition': typeof ToolBookletImpositionRoute
  '/_tool/cmyk-plates': typeof ToolCmykPlatesRoute
  '/_tool/dieline': typeof ToolDielineRoute
  '/_tool/dpi-calculator': typeof ToolDpiCalculatorRoute
  '/_tool/fold-simulator': typeof ToolFoldSimulatorRoute
  '/_tool/legibility': typeof ToolLegibilityRoute
  '/_tool/nesting-calc': typeof ToolNestingCalcRoute
  '/_tool/pdf-tools': typeof ToolPdfToolsRoute
  '/_tool/rgb-to-cmyk': typeof ToolRgbToCmykRoute
  '/_tool/screen-print': typeof ToolScreenPrintRoute
  '/_tool/spine-calculator': typeof ToolSpineCalculatorRoute
  '/_tool/spot-finish': typeof ToolSpotFinishRoute
  '/_tool/tac-checker': typeof ToolTacCheckerRoute
  '/_tool/textile-guide': typeof ToolTextileGuideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgu'
    | '/sitemap.xml'
    | '/barcode-generator'
    | '/bleed-generator'
    | '/booklet-imposition'
    | '/cmyk-plates'
    | '/dieline'
    | '/dpi-calculator'
    | '/fold-simulator'
    | '/legibility'
    | '/nesting-calc'
    | '/pdf-tools'
    | '/rgb-to-cmyk'
    | '/screen-print'
    | '/spine-calculator'
    | '/spot-finish'
    | '/tac-checker'
    | '/textile-guide'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgu'
    | '/sitemap.xml'
    | '/barcode-generator'
    | '/bleed-generator'
    | '/booklet-imposition'
    | '/cmyk-plates'
    | '/dieline'
    | '/dpi-calculator'
    | '/fold-simulator'
    | '/legibility'
    | '/nesting-calc'
    | '/pdf-tools'
    | '/rgb-to-cmyk'
    | '/screen-print'
    | '/spine-calculator'
    | '/spot-finish'
    | '/tac-checker'
    | '/textile-guide'
  id:
    | '__root__'
    | '/'
    | '/cgu'
    | '/sitemap.xml'
    | '/_tool/barcode-generator'
    | '/_tool/bleed-generator'
    | '/_tool/booklet-imposition'
    | '/_tool/cmyk-plates'
    | '/_tool/dieline'
    | '/_tool/dpi-calculator'
    | '/_tool/fold-simulator'
    | '/_tool/legibility'
    | '/_tool/nesting-calc'
    | '/_tool/pdf-tools'
    | '/_tool/rgb-to-cmyk'
    | '/_tool/screen-print'
    | '/_tool/spine-calculator'
    | '/_tool/spot-finish'
    | '/_tool/tac-checker'
    | '/_tool/textile-guide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CguRoute: typeof CguRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToolBarcodeGeneratorRoute: typeof ToolBarcodeGeneratorRoute
  ToolBleedGeneratorRoute: typeof ToolBleedGeneratorRoute
  ToolBookletImpositionRoute: typeof ToolBookletImpositionRoute
  ToolCmykPlatesRoute: typeof ToolCmykPlatesRoute
  ToolDielineRoute: typeof ToolDielineRoute
  ToolDpiCalculatorRoute: typeof ToolDpiCalculatorRoute
  ToolFoldSimulatorRoute: typeof ToolFoldSimulatorRoute
  ToolLegibilityRoute: typeof ToolLegibilityRoute
  ToolNestingCalcRoute: typeof ToolNestingCalcRoute
  ToolPdfToolsRoute: typeof ToolPdfToolsRoute
  ToolRgbToCmykRoute: typeof ToolRgbToCmykRoute
  ToolScreenPrintRoute: typeof ToolScreenPrintRoute
  ToolSpineCalculatorRoute: typeof ToolSpineCalculatorRoute
  ToolSpotFinishRoute: typeof ToolSpotFinishRoute
  ToolTacCheckerRoute: typeof ToolTacCheckerRoute
  ToolTextileGuideRoute: typeof ToolTextileGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/barcode-generator': {
      id: '/_tool/barcode-generator'
      path: '/barcode-generator'
      fullPath: '/barcode-generator'
      preLoaderRoute: typeof ToolBarcodeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/bleed-generator': {
      id: '/_tool/bleed-generator'
      path: '/bleed-generator'
      fullPath: '/bleed-generator'
      preLoaderRoute: typeof ToolBleedGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/booklet-imposition': {
      id: '/_tool/booklet-imposition'
      path: '/booklet-imposition'
      fullPath: '/booklet-imposition'
      preLoaderRoute: typeof ToolBookletImpositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/cmyk-plates': {
      id: '/_tool/cmyk-plates'
      path: '/cmyk-plates'
      fullPath: '/cmyk-plates'
      preLoaderRoute: typeof ToolCmykPlatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/dieline': {
      id: '/_tool/dieline'
      path: '/dieline'
      fullPath: '/dieline'
      preLoaderRoute: typeof ToolDielineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/dpi-calculator': {
      id: '/_tool/dpi-calculator'
      path: '/dpi-calculator'
      fullPath: '/dpi-calculator'
      preLoaderRoute: typeof ToolDpiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/fold-simulator': {
      id: '/_tool/fold-simulator'
      path: '/fold-simulator'
      fullPath: '/fold-simulator'
      preLoaderRoute: typeof ToolFoldSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/legibility': {
      id: '/_tool/legibility'
      path: '/legibility'
      fullPath: '/legibility'
      preLoaderRoute: typeof ToolLegibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/nesting-calc': {
      id: '/_tool/nesting-calc'
      path: '/nesting-calc'
      fullPath: '/nesting-calc'
      preLoaderRoute: typeof ToolNestingCalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/pdf-tools': {
      id: '/_tool/pdf-tools'
      path: '/pdf-tools'
      fullPath: '/pdf-tools'
      preLoaderRoute: typeof ToolPdfToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/rgb-to-cmyk': {
      id: '/_tool/rgb-to-cmyk'
      path: '/rgb-to-cmyk'
      fullPath: '/rgb-to-cmyk'
      preLoaderRoute: typeof ToolRgbToCmykRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/screen-print': {
      id: '/_tool/screen-print'
      path: '/screen-print'
      fullPath: '/screen-print'
      preLoaderRoute: typeof ToolScreenPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/spine-calculator': {
      id: '/_tool/spine-calculator'
      path: '/spine-calculator'
      fullPath: '/spine-calculator'
      preLoaderRoute: typeof ToolSpineCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/spot-finish': {
      id: '/_tool/spot-finish'
      path: '/spot-finish'
      fullPath: '/spot-finish'
      preLoaderRoute: typeof ToolSpotFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/tac-checker': {
      id: '/_tool/tac-checker'
      path: '/tac-checker'
      fullPath: '/tac-checker'
      preLoaderRoute: typeof ToolTacCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/textile-guide': {
      id: '/_tool/textile-guide'
      path: '/textile-guide'
      fullPath: '/textile-guide'
      preLoaderRoute: typeof ToolTextileGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CguRoute: CguRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToolBarcodeGeneratorRoute: ToolBarcodeGeneratorRoute,
  ToolBleedGeneratorRoute: ToolBleedGeneratorRoute,
  ToolBookletImpositionRoute: ToolBookletImpositionRoute,
  ToolCmykPlatesRoute: ToolCmykPlatesRoute,
  ToolDielineRoute: ToolDielineRoute,
  ToolDpiCalculatorRoute: ToolDpiCalculatorRoute,
  ToolFoldSimulatorRoute: ToolFoldSimulatorRoute,
  ToolLegibilityRoute: ToolLegibilityRoute,
  ToolNestingCalcRoute: ToolNestingCalcRoute,
  ToolPdfToolsRoute: ToolPdfToolsRoute,
  ToolRgbToCmykRoute: ToolRgbToCmykRoute,
  ToolScreenPrintRoute: ToolScreenPrintRoute,
  ToolSpineCalculatorRoute: ToolSpineCalculatorRoute,
  ToolSpotFinishRoute: ToolSpotFinishRoute,
  ToolTacCheckerRoute: ToolTacCheckerRoute,
  ToolTextileGuideRoute: ToolTextileGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
