/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TacCheckerRouteImport } from './routes/tac-checker'
import { Route as TextileGuideRouteImport } from './routes/textile-guide'
import { Route as ToolBarcodeGeneratorRouteImport } from './routes/_tool/barcode-generator'
import { Route as ToolBleedGeneratorRouteImport } from './routes/_tool/bleed-generator'
import { Route as ToolDpiCalculatorRouteImport } from './routes/_tool/dpi-calculator'
import { Route as ToolFoldSimulatorRouteImport } from './routes/_tool/fold-simulator'
import { Route as ToolNestingCalcRouteImport } from './routes/_tool/nesting-calc'
import { Route as ToolPdfToolsRouteImport } from './routes/_tool/pdf-tools'
import { Route as ToolRgbToCmykRouteImport } from './routes/_tool/rgb-to-cmyk'
import { Route as ToolSpineCalculatorRouteImport } from './routes/_tool/spine-calculator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TacCheckerRoute = TacCheckerRouteImport.update({
  id: '/tac-checker',
  path: '/tac-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const TextileGuideRoute = TextileGuideRouteImport.update({
  id: '/textile-guide',
  path: '/textile-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolBarcodeGeneratorRoute = ToolBarcodeGeneratorRouteImport.update({
  id: '/_tool/barcode-generator',
  path: '/barcode-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolBleedGeneratorRoute = ToolBleedGeneratorRouteImport.update({
  id: '/_tool/bleed-generator',
  path: '/bleed-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolDpiCalculatorRoute = ToolDpiCalculatorRouteImport.update({
  id: '/_tool/dpi-calculator',
  path: '/dpi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolFoldSimulatorRoute = ToolFoldSimulatorRouteImport.update({
  id: '/_tool/fold-simulator',
  path: '/fold-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolNestingCalcRoute = ToolNestingCalcRouteImport.update({
  id: '/_tool/nesting-calc',
  path: '/nesting-calc',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolPdfToolsRoute = ToolPdfToolsRouteImport.update({
  id: '/_tool/pdf-tools',
  path: '/pdf-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolRgbToCmykRoute = ToolRgbToCmykRouteImport.update({
  id: '/_tool/rgb-to-cmyk',
  path: '/rgb-to-cmyk',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSpineCalculatorRoute = ToolSpineCalculatorRouteImport.update({
  id: '/_tool/spine-calculator',
  path: '/spine-calculator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tac-checker': typeof TacCheckerRoute
  '/textile-guide': typeof TextileGuideRoute
  '/barcode-generator': typeof ToolBarcodeGeneratorRoute
  '/bleed-generator': typeof ToolBleedGeneratorRoute
  '/dpi-calculator': typeof ToolDpiCalculatorRoute
  '/fold-simulator': typeof ToolFoldSimulatorRoute
  '/nesting-calc': typeof ToolNestingCalcRoute
  '/pdf-tools': typeof ToolPdfToolsRoute
  '/rgb-to-cmyk': typeof ToolRgbToCmykRoute
  '/spine-calculator': typeof ToolSpineCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tac-checker': typeof TacCheckerRoute
  '/textile-guide': typeof TextileGuideRoute
  '/barcode-generator': typeof ToolBarcodeGeneratorRoute
  '/bleed-generator': typeof ToolBleedGeneratorRoute
  '/dpi-calculator': typeof ToolDpiCalculatorRoute
  '/fold-simulator': typeof ToolFoldSimulatorRoute
  '/nesting-calc': typeof ToolNestingCalcRoute
  '/pdf-tools': typeof ToolPdfToolsRoute
  '/rgb-to-cmyk': typeof ToolRgbToCmykRoute
  '/spine-calculator': typeof ToolSpineCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tac-checker': typeof TacCheckerRoute
  '/textile-guide': typeof TextileGuideRoute
  '/_tool/barcode-generator': typeof ToolBarcodeGeneratorRoute
  '/_tool/bleed-generator': typeof ToolBleedGeneratorRoute
  '/_tool/dpi-calculator': typeof ToolDpiCalculatorRoute
  '/_tool/fold-simulator': typeof ToolFoldSimulatorRoute
  '/_tool/nesting-calc': typeof ToolNestingCalcRoute
  '/_tool/pdf-tools': typeof ToolPdfToolsRoute
  '/_tool/rgb-to-cmyk': typeof ToolRgbToCmykRoute
  '/_tool/spine-calculator': typeof ToolSpineCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/tac-checker'
    | '/textile-guide'
    | '/barcode-generator'
    | '/bleed-generator'
    | '/dpi-calculator'
    | '/fold-simulator'
    | '/nesting-calc'
    | '/pdf-tools'
    | '/rgb-to-cmyk'
    | '/spine-calculator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/tac-checker'
    | '/textile-guide'
    | '/barcode-generator'
    | '/bleed-generator'
    | '/dpi-calculator'
    | '/fold-simulator'
    | '/nesting-calc'
    | '/pdf-tools'
    | '/rgb-to-cmyk'
    | '/spine-calculator'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/tac-checker'
    | '/textile-guide'
    | '/_tool/barcode-generator'
    | '/_tool/bleed-generator'
    | '/_tool/dpi-calculator'
    | '/_tool/fold-simulator'
    | '/_tool/nesting-calc'
    | '/_tool/pdf-tools'
    | '/_tool/rgb-to-cmyk'
    | '/_tool/spine-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TacCheckerRoute: typeof TacCheckerRoute
  TextileGuideRoute: typeof TextileGuideRoute
  ToolBarcodeGeneratorRoute: typeof ToolBarcodeGeneratorRoute
  ToolBleedGeneratorRoute: typeof ToolBleedGeneratorRoute
  ToolDpiCalculatorRoute: typeof ToolDpiCalculatorRoute
  ToolFoldSimulatorRoute: typeof ToolFoldSimulatorRoute
  ToolNestingCalcRoute: typeof ToolNestingCalcRoute
  ToolPdfToolsRoute: typeof ToolPdfToolsRoute
  ToolRgbToCmykRoute: typeof ToolRgbToCmykRoute
  ToolSpineCalculatorRoute: typeof ToolSpineCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tac-checker': {
      id: '/tac-checker'
      path: '/tac-checker'
      fullPath: '/tac-checker'
      preLoaderRoute: typeof TacCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textile-guide': {
      id: '/textile-guide'
      path: '/textile-guide'
      fullPath: '/textile-guide'
      preLoaderRoute: typeof TextileGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/barcode-generator': {
      id: '/_tool/barcode-generator'
      path: '/barcode-generator'
      fullPath: '/barcode-generator'
      preLoaderRoute: typeof ToolBarcodeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/bleed-generator': {
      id: '/_tool/bleed-generator'
      path: '/bleed-generator'
      fullPath: '/bleed-generator'
      preLoaderRoute: typeof ToolBleedGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/dpi-calculator': {
      id: '/_tool/dpi-calculator'
      path: '/dpi-calculator'
      fullPath: '/dpi-calculator'
      preLoaderRoute: typeof ToolDpiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/fold-simulator': {
      id: '/_tool/fold-simulator'
      path: '/fold-simulator'
      fullPath: '/fold-simulator'
      preLoaderRoute: typeof ToolFoldSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/nesting-calc': {
      id: '/_tool/nesting-calc'
      path: '/nesting-calc'
      fullPath: '/nesting-calc'
      preLoaderRoute: typeof ToolNestingCalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/pdf-tools': {
      id: '/_tool/pdf-tools'
      path: '/pdf-tools'
      fullPath: '/pdf-tools'
      preLoaderRoute: typeof ToolPdfToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/rgb-to-cmyk': {
      id: '/_tool/rgb-to-cmyk'
      path: '/rgb-to-cmyk'
      fullPath: '/rgb-to-cmyk'
      preLoaderRoute: typeof ToolRgbToCmykRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tool/spine-calculator': {
      id: '/_tool/spine-calculator'
      path: '/spine-calculator'
      fullPath: '/spine-calculator'
      preLoaderRoute: typeof ToolSpineCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TacCheckerRoute: TacCheckerRoute,
  TextileGuideRoute: TextileGuideRoute,
  ToolBarcodeGeneratorRoute: ToolBarcodeGeneratorRoute,
  ToolBleedGeneratorRoute: ToolBleedGeneratorRoute,
  ToolDpiCalculatorRoute: ToolDpiCalculatorRoute,
  ToolFoldSimulatorRoute: ToolFoldSimulatorRoute,
  ToolNestingCalcRoute: ToolNestingCalcRoute,
  ToolPdfToolsRoute: ToolPdfToolsRoute,
  ToolRgbToCmykRoute: ToolRgbToCmykRoute,
  ToolSpineCalculatorRoute: ToolSpineCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
